allowBuilds:
  '@parcel/watcher': true
  puppeteer: true
ignoredBuiltDependencies:
  - '@parcel/watcher'

minimumReleaseAgeExclude:
  - eslint-config-reverentgeek@7.1.8

onlyBuiltDependencies:
  - puppeteer
