allowBuilds:
  '@parcel/watcher': true
  puppeteer: true
ignoredBuiltDependencies:
  - '@parcel/watcher'

minimumReleaseAgeExclude:
  - eslint-config-reverentgeek
  - '@pnpm/exe.android-arm64@12.11.2'
  - '@pnpm/exe.android-x64@12.11.2'
  - '@pnpm/exe.darwin-arm64@12.11.2'
  - '@pnpm/exe.darwin-x64@12.11.2'
  - '@pnpm/exe.freebsd-x64@12.11.2'
  - '@pnpm/exe.linux-arm64-musl@12.11.2'
  - '@pnpm/exe.linux-arm64@12.11.2'
  - '@pnpm/exe.linux-ppc64@12.11.2'
  - '@pnpm/exe.linux-riscv64@12.11.2'
  - '@pnpm/exe.linux-s390x@12.11.2'
  - '@pnpm/exe.linux-x64-musl@12.11.2'
  - '@pnpm/exe.linux-x64@12.11.2'
  - '@pnpm/exe.win32-arm64@12.11.2'
  - '@pnpm/exe.win32-x64@12.11.2'
  - pnpm@12.11.2

onlyBuiltDependencies:
  - puppeteer
