const chordRegEx = /^(?<flatted>[b#]{0,1})(?<root>[A-G1-7][#♯b♭]?(m(?!aj)|maj)?)(?<quality>(2|3|4|5|6|7|9|\(|\)|no|o|\+|add|dim|sus|aug){0,5})$/;
const siteHost = "charter.reverentgeek.com";
const htmlEntities = { "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&#34;", "'": "&#39;" };

export function escapeHtml( text ) {
	return String( text ?? "" ).replace( /[&<>'"]/g, c => htmlEntities[c] );
}

function renderHeader( chart ) {
	const header = [];
	header.push( "<span class=\"charter-song-header\">" );
	header.push( "<span class=\"charter-title-wrapper\">" );
	header.push( `<span class="charter-title">${ escapeHtml( chart.title ) }</span>` );
	header.push( "</span>" ); // charter-title-wrapper
	chart.artist.forEach( ( artist ) => {
		header.push( `<span class="charter-artist-wrapper"><span class="charter-artist">${ escapeHtml( artist ) }</span></span>` );
	} );
	if ( chart.subtitle ) {
		header.push( `<span class="charter-sub-title">${ escapeHtml( chart.subtitle ) }</span>` );
	}
	const keyLine = [];
	if ( chart.key ) {
		keyLine.push( `Key: ${ chart.key }` );
	}
	if ( chart.tempo ) {
		keyLine.push( `Tempo: ${ chart.tempo }` );
	}
	if ( chart.time ) {
		keyLine.push( `Time: ${ chart.time }` );
	}
	if ( keyLine.length > 0 ) {
		header.push( `<div class="charter-song-key-tempo-wrapper"><span class="charter-song-key-tempo">${ escapeHtml( keyLine.join( " | " ) ) }</span></div>` );
	}
	header.push( "</span>" ); // charter-song-header
	return header.join( "\n" );
}

function renderPage( chart, body, { css } ) {
	const page = [];
	page.push( "<!DOCTYPE html>" );
	page.push( "<html>" );
	page.push( "<head>" );
	page.push( "<meta charset=\"utf-8\">" );
	page.push( "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">" );
	page.push( `<title>${ escapeHtml( chart.title ) }</title>` );
	page.push( css ? `<style>\n${ css }\n</style>` : "<link rel=\"stylesheet\" href=\"./assets/styles.css\">" );
	page.push( "</head>" );
	page.push( "<body>" );
	page.push( "<div id=\"charter-container\">" );
	page.push( renderHeader( chart ) );
	page.push( "<br>" );
	page.push( body );
	page.push( `<div class="charter-credit">Generated by <a href="https://${ siteHost }">${ siteHost }</a></div>` );
	page.push( "</div>" );
	page.push( "</body>" );
	page.push( "</html>" );
	return page.join( "\n" );
}

function parseChord( chord ) {
	const match = chord.match( chordRegEx );
	if ( !match || !match.groups ) {
		return {
			flatted: "",
			root: chord,
			quality: ""
		};
	}
	const g = match.groups;
	return {
		flatted: g["flatted"] ?? "",
		root: g["root"] ?? "",
		quality: g["quality"] ?? ""
	};
}

export function formatChord( chord ) {
	if ( chord.length <= 1 || chord === "N.C." ) {
		return escapeHtml( chord );
	}
	// Strip grouping parentheses that indicate optional/passing chords.
	// They can fully wrap a chord like (1/3), or span across chords like (4 ... 2m7)
	// Quality parens mid-chord like 42(no3) or C(add9) must NOT be stripped.
	const hasLeadingParen = chord.startsWith( "(" );
	const hasTrailingParen = chord.endsWith( ")" );
	const hasInnerParen = chord.indexOf( "(", hasLeadingParen ? 1 : 0 ) > 0;
	const prefix = hasLeadingParen ? "(" : "";
	const suffix = hasTrailingParen && !hasInnerParen ? ")" : "";
	const inner = chord.slice( prefix.length, chord.length - suffix.length ) || chord;
	const chords = inner.split( "/" );
	const formatted = chords.map( ( c ) => {
		const { flatted, root, quality } = parseChord( c );
		const html = `${ flatted }${ escapeHtml( root ) }${ quality ? "<sup>" + quality + "</sup>" : "" }`;
		return html;
	} );
	const result = formatted.length > 1 ? formatted.join( "/" ) : formatted[0];
	return `${ prefix }${ result }${ suffix }`;
}

function renderLyricLine( body, lyric, chord, direction ) {
	if ( chord ) {
		body.push( `<span class="charter-chord-wrapper"><span class="charter-chord">${ formatChord( chord ) }</span>` );
		body.push( `<span class="charter-chord-lyric">${ lyric.length > 0 ? escapeHtml( lyric ) : " " }</span>` );
		body.push( "</span>" );
		if ( lyric.trim() === "" ) body.push( "    " );
	} else if ( direction ) {
		body.push( `<span class="charter-direction-wrapper"><span class="charter-direction">${ escapeHtml( direction ) }</span></span>` );
	} else {
		body.push( escapeHtml( lyric ) );
	}
}

export function totalLines( sections ) {
	let count = 0;
	sections.forEach( section => count += section.lyrics.length + 1 );
	return count;
}

export function getColumnBreak( sections ) {
	if ( sections.length < 2 ) return 0;
	if ( sections.length === 2 ) return 1;
	const right = [];
	const left = [ ...sections ];
	for ( let i = sections.length - 1; i > 0; i-- ) {
		right.push( left.pop() );
		if ( totalLines( right ) === totalLines( left ) ) return i;
		if ( totalLines( right ) >= totalLines( left ) ) return i + 1;
	}
}

// options.css inlines a stylesheet instead of linking ./assets/styles.css
export function render( chart, options = {} ) {
	const { columns = false, css = "" } = options;
	const columnBreak = columns ? getColumnBreak( chart.sections ) : 0;
	const body = [];
	if ( chart.sections.length > 0 ) {
		body.push( "<pre class=\"charter-song-body\">" );
		chart.sections.forEach( ( section, index ) => {
			if ( columnBreak > 0 && index === 0 ) {
				body.push( "<span class=\"charter-column left-column\">" );
			}
			if ( columnBreak > 0 && columnBreak === index ) {
				body.push( "</span><span class=\"charter-column right-column\">" );
			}
			body.push( "<span class=\"charter-section-wrapper\">" );
			if ( section.title ) {
				body.push( `<span class="charter-section-title">${ escapeHtml( section.title ) }</span>` );
			}
			for ( let i = 0; i < section.chords.length; i++ ) {
				if ( i > 0 ) body.push( "\n" );
				body.push( "<span class=\"charter-song-line\">" );
				for ( let j = 0; j < section.chords[i].length; j++ ) {
					renderLyricLine( body, section.lyrics[i][j], section.chords[i][j], section.directions[i][j] );
				}
				body.push( "</span>" ); // charter-song-line
			}
			body.push( "</span>" ); // charter-section-wrapper
			if ( index !== chart.sections.length - 1 ) {
				body.push( "\n\n" );
			}
		} );
		if ( columnBreak > 0 ) {
			body.push( "</span>" ); // charter-column
		}
		body.push( "</pre>" ); // charter-song-body
	}
	return renderPage( chart, body.join( "" ), { css } );
}
